language: node_js
node_js:
- 6.1.0
deploy:
  provider: heroku
  api_key:
    secure: mrLK44ewZob83vf3eTWYHGpqdaTUfZlgrK5KzyETivRWb0N7EbMpXNqqwnfpZKOug6LWTBPjObJuMvfvhtFc0ErPw8aTpiXmP2knKcAHjbfIj8mOvqh8w6sPPOp95nLqOrBGpL/Awob8KsIyNLZ/tfKExdGG/UZRC7YUlW1Jp0vxw7H0c4CD1JWMUOxApZwE+7Ha3/8hT7pfAsTtwwe5JlqMwpJXDPeYAwxMfyLkK2JLfxvHGQJC2q3o6OJw9GDmN2Sgfj9kMZhza6FDFjp5cny+Z0h5ZnvGMEJJEGJz6ZO2Ce0z6F4KQheFdvV7tOKJwBGH6GHBnvaNkchP058M9hqdrQXRM4ira7munXi9BzG6QSQ3Rx949V2y5uYv+fRhHsFl+BcPMIL7Gx828TVRqEtrHcwupKiedzUyYiWKU2KoqFMCx4/lkRD58V/2VLHUNFi1Ii9b/2qjbJ/s8XWr/9GfwlvE3MR3Jht2I1sA6ouT8hMKZiYo3e/e0yHepyBEEvS2dHbhSzhf7IfXVTDfTU2dlNP3ru1/tGWfYK4H94jwnYPul0snNQGrlEPKQ5J4Zpwpg9wrR0vKliccbVCZApkOj+7LmuYXLP5Dmabp8cA6Ze9ev+4Rp4h5UWXJxFvARmwlYpkaMHUQUA3n2c5q1jzX+fEGEsWo0U0sgl5707I=
